name: CI

on:
  push:
    branches:
      - main
    paths:
      - application/**
      - .github/workflows/ci.yaml
  pull_request:
    branches:
      - main
    paths:
      - application/**
      - .github/workflows/ci.yaml

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: application
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm ci
      - run: npm run ci
      - run: npm run build
      - run: npm run build
        env:
          VITE_SERVER_ENTRY: ./app/entrypoint.local.ts
      - run: npm run package
      - run: unzip -l lambda.zip
      - run: unzip -t lambda.zip
